project:
  type: website

website:
  title: "Sepsis Survival Predictions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Graphs
        menu: 
          - href: episodes.qmd
            text: Episode Numbers
          - href: ages.qmd
            text: Ages
          - href: gender.qmd
            text: Genders
      - href: about.qmd
        text: About
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



