---
title: "Main model"
execute: 
  echo: false
  warning: false
---

```{r}
#| label: Setup
#| message: false
# Load in all the libraries that may be used 
library(tidyverse)
library(gtsummary)
library(tidybayes)
library(brms)
library(broom.mixed)
# Read in the data
sepsis_data <- read.csv("data/s41598-020-73558-3_sepsis_survival_primary_cohort.csv")
```

```{r}
# Mutate and edit the data
#| label: edit data
sepsis_data <- sepsis_data |>
# Rework the sex column to make more sense
  mutate(
# Make cloumn names shorter and easier to work with
    age = age_years,
    sex = factor(sex_0male_1female, labels = c("Male", "Female")),
    outcome = hospital_outcome_1alive_0dead
  )

```


```{r}
#| label: model
#| cache: true
#| message: false
#| warnings: false
# Make the model with all covariates to outcome.
fit_sepsis <- brm(
  formula = outcome ~ age + sex + episode_number,
  family = bernoulli(link = "logit"),
  data = sepsis_data,
  silent = 2, 
  refresh = 0)

```


```{r}
#| label: make new object
# Generate new observations for prediction
newobs <- expand.grid(
  episode_number = c(1, 2, 3, 4, 5), 
  sex = c("Male", "Female"), 
  # use average age
  age = mean(sepsis_data$age)
)

```
$$
\text{logit}(\pi_i) = \beta_0 + \beta_1 \cdot \text{age}_i + \beta_2 \cdot \text{sex}_{i,\text{Male}} + \beta_3 \cdot \text{episode\_number}_i
$$

```{r}
#| label: table
#| warning: false
tbl_regression(fit_sepsis)
```


```{r}
#| label: plot

fit_sepsis |> 
  add_epred_draws(newdata = newobs) |>
# Make the graph with x as the predicted surrvival rate, y as the episode numbers, and color as the sex
  ggplot(aes(x = .epred, y = as.factor(episode_number), fill = sex)) + 
# Chose to make stat_slab
  stat_slab(alpha = 0.5, position = "identity") + 
# Manually add colors for better customizatino
  scale_fill_manual(values = c("Male" = "cornflowerblue", "Female"  = "darkred")) + 
# Change x-axis labels to percent format
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) +
# Add labels and key
  labs(
    title = "Probability of Surviving by Episode Number and Gender",
    x = "Predicted Probability of Surviving (%)",
    y = "Episode Number",
    fill = "Sex"
  ) +
# Make a cleaner theme
  theme_minimal() +
  theme(legend.position = "bottom")

```

